/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_offis_faint_detection_plugins_opencv_OpenCVDetection */

#ifndef _Included_de_offis_faint_detection_plugins_opencv_OpenCVDetection
#define _Included_de_offis_faint_detection_plugins_opencv_OpenCVDetection
#ifdef __cplusplus
extern "C" {
#endif
#undef de_offis_faint_detection_plugins_opencv_OpenCVDetection_serialVersionUID
#define de_offis_faint_detection_plugins_opencv_OpenCVDetection_serialVersionUID 9040924330337550071i64
/*
 * Class:     de_offis_faint_detection_plugins_opencv_OpenCVDetection
 * Method:    detectFacesJNI
 * Signature: (Ljava/lang/String;Lde/offis/faint/detection/plugins/opencv/OpenCVDetection;)[Lde/offis/faint/model/Region;
 */
JNIEXPORT jobjectArray JNICALL Java_de_offis_faint_detection_plugins_opencv_OpenCVDetection_detectFacesJNI
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
