/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class faint_OpenCV */

#ifndef _Included_faint_OpenCV
#define _Included_faint_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     faint_OpenCV
 * Method:    detectFaces
 * Signature: (Ljava/lang/String;)[Lfaint/Region;
 */
JNIEXPORT jobjectArray JNICALL Java_faint_OpenCV_detectFaces
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
